services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db postgres
    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-username}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-userpass}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-username} -d ${DB_DATABASE:-laravel}"]
            interval: 5s
            retries: 10
        ports:
            - "5432:5432"
        networks:
            - laravel

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge